version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = false
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v22iqzkm2jsb"
s3_prefix = "sam-app"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
